try another approach

diff --git a/.github/workflows/integration-placement.yaml b/.github/workflows/integration-placement.yaml
--- a/.github/workflows/integration-placement.yaml
+++ b/.github/workflows/integration-placement.yaml
@@ -28,12 +28,12 @@ jobs:
           enabled_services: "${{ matrix.additional_services }}"
           # since the local.conf is parsed as shell script, use it to create an additional config file.
           conf_overrides: |
-            [[post-config|\$NOVA_CONF]]
+            [[post-config|$NOVA_CONF]]
             [compute]
-            provider_config_location = $PWD/provider_config/
+            provider_config_location = /tmp/provider_config/
 
-            mkdir -p $PWD/provider_config/
-            cat > $PWD/provider_config//traits.yaml << 'EOF_PROVIDER'
+            mkdir -p /tmp/provider_config
+            cat > /tmp/provider_config/traits.yaml << 'EOF_PROVIDER'
             meta:
               schema_version: "1.0"
             providers:
@@ -54,7 +54,7 @@ jobs:
       - name: Display traits.yaml configuration
         run: |
           echo "Contents of traits.yaml:"
-          cat $PWD/provider_config//traits.yaml || echo "File $PWD/provider_config//traits.yaml not found"
+          cat /tmp/provider_config/traits.yaml || echo "File /tmp/provider_config/traits.yaml not found"
       - name: Run Openstack Integration Tests
         run: bash ./script/integration-suites/placement
         env:
